### ISSUE TITLE
The problem about training

### ISSUE THREAD

**Issue by LinZhuoChen** [fate3439/LocalSpecGCN#1]
How many time should I need to get the result of shapenet in paper?
I found that the training time is too long in Titan Xp.I was wonding I make some mistake
Thank you !

**Comment by fate3439** [comment]
Less than 24 hours for sure.
100 epochs.

Sent from my iPhone

On Aug 14, 2018, at 1:09 AM, LinZhuoChen <notifications@github.com<mailto:notifications@github.com>> wrote:


How many time should I need to get the result of shapenet in paper?
I found that the training time is too long in Titan Xp.I was wonding I make some mistake
Thank you !
