### ISSUE TITLE
can you help me?how to solve this problem?

### ISSUE THREAD

**Issue by longmalongma** [fate3439/LocalSpecGCN#10]
InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:590: cuSolverDN call failed with status =6

**Comment by fate3439** [comment]
This is more likely a tf related issue, not specifically to my implementation.

**Comment by dangjisheng** [comment]
> This is more likely a tf related issue, not specifically to my implementation.

Sorry,I do not think so.Beacuse I can make it for pointnet++'code,only when I use your the model of pointnet2_cls_ssg_spec_cp.py ,I meet this problem ,I can not solve this problem
InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:590: cuSolverDN call failed with status =6
	 [[Node: layer4/SelfAdjointEigV2 = SelfAdjointEigV2[T=DT_FLOAT, compute_v=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](layer4/sub_1)]]
	 [[Node: Mean/_43 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1377_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by fate3439** [comment]
I am sorry I have never seen this problem during my experiments using this repo. I hope you can find other resources to help you...
