### ISSUE TITLE
One drive link deprecated ?

### ISSUE THREAD

**Issue by utayao** [fate3439/LocalSpecGCN#2]
I am very interested in your work, but I find the one drive link to download the data is deprecated. Can you share the data using other ways ? Thanks.

**Comment by fate3439** [comment]
Hi I think it is the best that you contact Charles Qi for this matter. It is his data.

Best,
Chu.

Sent from my iPhone

On Sep 14, 2018, at 12:28 PM, Jiawen Yao <notifications@github.com<mailto:notifications@github.com>> wrote:


I am very interested in your work, but I find the one drive link to download the data is deprecated. Can you share the data using other ways ? Thanks.

**Comment by fate3439** [comment]
Another alternative I can think of is to directly sample points from the meshes in ModelNet40. Some very handy libraries for your reference: 
1. open3D: http://www.open3d.org/ 
2. pyntcloud: https://github.com/daavoo/pyntcloud
I am sure pyntcloud supports points sampling as well as acquiring surface normals on each point.
