### ISSUE TITLE
How can I get the result of pointnet2_cls_ssg.py reported in paper?

### ISSUE THREAD

**Issue by LinZhuoChen** [fate3439/LocalSpecGCN#3]
The result in paper is 90.6% without normal, how can I modify the configuration to get the result in paper?

**Comment by LinZhuoChen** [comment]
Thank You!

**Comment by LinZhuoChen** [comment]
I can only get 89.7% without normal, I don't know why

**Comment by fate3439** [comment]
For that result entry, which belongs to pointnet++, please refer to their repo and contact the authors. I remember using a eval script on top of the trained model helps. You can refer to their eval script for a reference.

Sent from my iPhone

On Oct 19, 2018, at 9:37 AM, LinZhuoChen <notifications@github.com<mailto:notifications@github.com>> wrote:


I can only get 89.7% without normal, I don't know why

**Comment by LinZhuoChen** [comment]
I run the  pointnet2_cls_ssg.py which is the modified pointnet++ with 4 layers and can't get the result, how did you get that result reported in paper which is 90.6% with 4l-pointnet++? Thank you!

**Comment by fate3439** [comment]
Like I said, I used the eval script provided in pointnet++ repo and simply run it on 3l-pn++ and 4l-pn++ to get the result in our paper(Table 2). The results reported in pn++ and Table 2 are evaluated using multiple views at test time, again, please refer to pn++ repo. And for the eval script related question, I suggest you post issue on their repo. Good luck!
