### ISSUE TITLE
the problem about pooling

### ISSUE THREAD

**Issue by linluck1027** [fate3439/LocalSpecGCN#6]
I meet issue when run program
the error is :
I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x562579880430

**Comment by fate3439** [comment]
Hi,

The error does not seem to be related to my implementation, but rather seems to be a cuda issue. Also I am not an expert in debugging and so I may not be able to help you on these kind of issues...
