### ISSUE TITLE
程序一直停在这里，很长时间才运行一点。与MLP的速度，完全不能比，怎么办？？

### ISSUE THREAD

**Issue by xuesanshi** [fate3439/LocalSpecGCN#8]
![image](https://user-images.githubusercontent.com/42695993/57593403-d3fd7900-756d-11e9-9820-09677210374b.png)

**Comment by fate3439** [comment]
emm... I think this is a tensorflow issue instead of issues specific to this code base? I am not an expert in bebugging tf so I am sorry I can't help.
