### ISSUE TITLE
Questions about Evaluations of the Experiments

### ISSUE THREAD

**Issue by limt15** [fate3439/LocalSpecGCN#9]
Hi, Chu Wang
Thank you for sharing the code of the LocalSpecGCN.
I have finished the train of the classification and the part segmentation, then I found there is no `evaluate.py` for the trained model.
Could you share the evaluation code and experiments of LocalSpecGCN?
And, could you update the Scannet experiment details?
Looking forward for your reply!
Best regards !

**Comment by fate3439** [comment]
Hi,

IF I remember correct, there wasn't a specific eval script for the classification task. In stead, you can monitor the max classification results in the training script. That was how I reported the results as well.

That being said, I can go back and dig into my code and find if there is anything similar to your request.

**Comment by limt15** [comment]
Hi, Chu Wang
Thank you for your reply!
That is to say, after the training experiment finished, the recorded results of the `EPOCH 250` in the path`classification/log/spec_cp/log_train.txt` is the last and best evaluation result of  the classification experiment on `Modelnet40`, which is the final result reported in your paper . As well as the part segmentation experiment?

Ps: I was doubt about it because the `pointnet2` project shares the `evaluation.py`script for experiments on classification and segmentation.

I wonder whether i understand it correctly~

Looking forward for your reply!
Best regards !

**Comment by fate3439** [comment]
No, you would have to write a minor function to monitor best eval set performance during the training to acquire the reported result. Actually, our training script is based on pointnet++'s, so I suppose it wont take too much work to port the eval script there to this code base.

Good luck!

**Comment by limt15** [comment]
Thank you~
I guess that the best result of EPOCH through the training process has been recorded in the `classification/log/spec_cp/log_max_record.txt`, does it right?

**Comment by fate3439** [comment]
Yes right.
